kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: platform-bpmn
    component: platform-bpmn
    tier: frontend
  name: platform-bpmn
  namespace: resource-platform
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: platform-bpmn
      component: platform-bpmn
      tier: frontend
  template:
    metadata:
      labels:
        app: platform-bpmn
        component: platform-bpmn
        tier: frontend
    spec:
      #      imagePullSecrets:
      #        - name: $DOCKER_CREDENTIAL_ID
      containers:
        - name: platform-bpmn
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform-bpmn
    component: platform-bpmn
  name: platform-bpmn
  namespace: resource-platform
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30777
  selector:
    app: platform-bpmn
    component: platform-bpmn
    tier: frontend
  sessionAffinity: None
  type: NodePort
